<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali ke beranda</name>
   <tag></tag>
   <elementGuidId>7576ba6b-7bb9-4c98-9947-2da4e1a0a84b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/section/div[2]/div/div/div/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78d2a90a-a502-445b-bcdf-496b03a5d23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap py-2 px-7 border rounded-lg text-white bg-secondary-70 hover:bg-secondary-40 text-base font-bold</value>
      <webElementGuid>67dfb558-120c-45d4-8761-431c71e46afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali ke beranda</value>
      <webElementGuid>9c70477c-e21f-4a71-8189-92d853cf9de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/section[@class=&quot;flex justify-center items-center lg:h-screen bg-[#EBEBED]&quot;]/div[@class=&quot;justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none tracking-wide&quot;]/div[@class=&quot;relative w-auto my-6 mx-auto max-w-3xl&quot;]/div[@class=&quot;border-0 p-3 md:p-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none&quot;]/div[@class=&quot;flex flex-col sm:flex-row justify-center items-center md:m-8 space-x-4&quot;]/div[@class=&quot;flex flex-col text-paletteText-primary space-y-6 w-[314px] max-w-[314px]&quot;]/div[@class=&quot;flex justify-center sm:justify-end space-x-4&quot;]/button[@class=&quot;whitespace-nowrap py-2 px-7 border rounded-lg text-white bg-secondary-70 hover:bg-secondary-40 text-base font-bold&quot;]</value>
      <webElementGuid>be0d6627-c898-4997-8ebf-b644974dfc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/section/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>d9b0f9a3-a0a1-4e59-9771-434850189a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima kasih telah melakukan registrasi, cek email Anda untuk melakukan aktivasi akun PaDi UMKM'])[1]/following::button[1]</value>
      <webElementGuid>7af7902e-c16e-4b1c-8274-1fed8a843b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Email Anda'])[1]/following::button[1]</value>
      <webElementGuid>eabab11c-9e27-4170-b97d-1ba7cf4e9635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali ke beranda']/parent::*</value>
      <webElementGuid>b64c2738-d290-45bc-82c4-8235f9e8b24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>766db6ad-9ba4-4568-8746-384b398ef268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Kembali ke beranda' or . = 'Kembali ke beranda')]</value>
      <webElementGuid>363d7b4f-9a81-44ee-91fc-cdf02c5d39ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
