<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_phonenumber</name>
   <tag></tag>
   <elementGuidId>5dbe7c27-3e59-4e6d-8d47-4fe903eb96f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phonenumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phonenumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f53f927f-d1e0-407d-b158-957b34aefdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>11e03525-49ab-42b1-adb2-f26066aea61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 text-paletteText-primary text-sm w-full focus:outline-none</value>
      <webElementGuid>34db4419-afa8-4763-8392-7b434bfc8f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>d4498a55-3c9e-4cb8-8f8a-fa27f4fd97e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>563bbfeb-b20b-4f88-a6f1-f6ffba2f13fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>feb06cba-b01d-431e-849b-1f4060fee37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123456789</value>
      <webElementGuid>5b2d02a4-1c2d-4f15-82e3-c84edb3adaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>50f1698e-e86f-425a-b0c4-3495982b5daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phonenumber&quot;)</value>
      <webElementGuid>c2673e8c-a5a7-485c-a6b1-a649ab1584d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phonenumber']</value>
      <webElementGuid>bfedb924-0fe5-4b21-be9b-b87ee3f17daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/section/div/div/form/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>8d9276d6-51e0-4f4c-9c72-557d56c6114f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>79bf397d-4981-4009-ae0e-10fa4a0c7e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phonenumber' and @name = 'phonenumber' and @type = 'text' and @placeholder = '8123456789']</value>
      <webElementGuid>3e45dcae-e05f-4972-9c19-9b68073c3aeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
