<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sign_in</name>
   <tag></tag>
   <elementGuidId>8189f984-5ea5-49e4-9d44-392c48378b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-lg.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Sign in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a04dfa8-02fd-40f1-bbb5-02e0d915fa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-danger</value>
      <webElementGuid>d437f022-4292-4d03-b84c-924dc2365933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bd35fe2e-9bb2-431b-9cab-2a6bbafe3549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>f13c17c9-4171-4bbc-819c-19b8bfc4190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 mx-auto&quot;]/div[@class=&quot;row no-gutters login-box&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;forms&quot;]/div[@class=&quot;form-content&quot;]/div[@class=&quot;login-form pb-5&quot;]/form[1]/div[@class=&quot;input-boxes&quot;]/div[@class=&quot;button input-box&quot;]/input[@class=&quot;btn btn-lg btn-danger&quot;]</value>
      <webElementGuid>b283e0d3-d173-470c-a3ff-b146bb6dafa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Sign in']</value>
      <webElementGuid>4ceefd43-b167-4302-85bc-348944a54e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ad2fd93a-5c8c-40b4-81ba-420128d6badc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>99215ca7-8f62-4fdb-9936-10ce9262bd2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
