<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_wrong_email_or_password</name>
   <tag></tag>
   <elementGuidId>303ba6ab-ef68-4efb-8303-937c5aa94750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-xs.text-left.text-paletteText-primary.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6867225f-4f16-4c3b-8806-9b5e8a55a9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs text-left text-paletteText-primary w-full</value>
      <webElementGuid>f5231c89-edac-44be-849f-e9f2fc5617f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tolong periksa kembali email dan kata sandi Anda.</value>
      <webElementGuid>ae964589-87d6-4789-9e1e-6dd93f2388dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex justify-center items-center min-h-screen bg-login-wrapper&quot;]/div[@class=&quot;max-w-screen-lg w-full bg-white lg:rounded-lg lg:flex overflow-hidden&quot;]/div[@class=&quot;flex flex-col justify-center items-center lg:w-3/6 w-full h-full py-10 lg:px-24 px-10 space-y-4 my-auto&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;bg-accent-error-10 h-full w-full flex items-center justify-between py-4 px-3 rounded-xl space-x-2&quot;]/div[@class=&quot;text-xs text-left text-paletteText-primary w-full&quot;]</value>
      <webElementGuid>3073887c-0357-4589-96a4-c6f90874f46c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[2]/div[2]/div/div</value>
      <webElementGuid>d777a84f-421d-43e2-b021-5b38627db198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[4]</value>
      <webElementGuid>ad8ac87a-fded-4fca-af48-597e359481a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Invoice Financing >'])[1]/following::div[13]</value>
      <webElementGuid>7131e04f-5380-46c1-9317-7777af821b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email'])[1]/preceding::div[1]</value>
      <webElementGuid>815a7af1-7a50-4f1a-a721-b08f37ff3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::div[2]</value>
      <webElementGuid>fe23ad75-6e90-4978-adda-b7ebb782bb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tolong periksa kembali email dan kata sandi Anda.']/parent::*</value>
      <webElementGuid>f22064f1-d545-412d-b60a-8056d5311f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>69b6d97e-1890-4d06-8682-1a92e77a26e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tolong periksa kembali email dan kata sandi Anda.' or . = 'Tolong periksa kembali email dan kata sandi Anda.')]</value>
      <webElementGuid>c8d0ac14-1db6-46f0-98ef-d3a368f1e48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
