<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload_video</name>
   <tag></tag>
   <elementGuidId>8b640cd5-66b1-4bb5-9937-7793d0dfa338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'product_video' and @type = 'file']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;product_video&quot;][@type=&quot;file&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_video</value>
      <webElementGuid>a1c34bf4-2169-4872-9c94-7b17a93cd300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0f0164de-8162-4774-8439-312c8c74060e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
