<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_popup_dashboard</name>
   <tag></tag>
   <elementGuidId>7528d58e-d3ba-4ea9-acda-220b7b12f381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='dibatalkan otomatis'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>0a7f4473-eca6-4919-8d8f-2b7a6e47eba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer </value>
      <webElementGuid>238fde11-950c-4188-84be-ab8d7a839d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2817d3dc-8722-40d2-b638-0f493a87eb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>da47a815-8772-44c8-8f5a-b47ef4552a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>931cade2-40c6-44a9-becf-a6e275ba87fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7aadbddd-a2b0-4b79-af86-852aee65e24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>04303a47-fad5-4f4c-805e-ce283558465a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none&quot;]/div[@class=&quot;relative w-auto my-2 mx-auto p-5&quot;]/div[@class=&quot;border-0 rounded-lg shadow-lg flex flex-col w-full bg-white outline-none focus:outline-none lg:min-w-[554px] p-8 max-w-[1000px]&quot;]/div[@class=&quot;flex flex-col items-start gap-6 w-[300px] md:w-[530px]&quot;]/div[@class=&quot;w-full flex justify-between items-center p-0&quot;]/svg[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>b6e37cec-2b25-4162-bcd1-eb40ffb70e28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dibatalkan otomatis'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>fd34d886-b8c2-482d-b909-6d6b7f2a0255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batas maks 2x24 jam (hari kerja; Senin s.d. Jumat)'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>cbdeb0c1-e2ae-4572-9768-862cddcda180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
