<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_barang</name>
   <tag></tag>
   <elementGuidId>fe5fa74e-4ca1-4108-8acd-da4d6895d6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;product_type&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='product_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9e1b0a2-dd78-4a2d-9021-80995f80ac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 w-full h-full bg-transparent</value>
      <webElementGuid>32aa9ac4-5164-446e-952c-6fecaaef8015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_type</value>
      <webElementGuid>60b6e40b-fba3-43b2-9b15-c22bb7be447e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b48aec2-57dc-489a-8339-066ec4fa1ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex-row justify-center items-between lg:h-screen bg-white text-paletteText-primary&quot;]/div[@class=&quot;flex relative w-full&quot;]/div[@class=&quot;w-full lg:px-[30px] lg:py-[24px] px-4 py-4&quot;]/div[@class=&quot;w-full bg-white shadow-[0_0_10px_rgba(0,0,0,0.15)] rounded-md lg:px-[30px] lg:py-[24px] px-4 py-4 space-y-4 mb-8&quot;]/div[@class=&quot;w-full lg:flex justify-between lg:space-x-4 space-y-4 lg:space-y-0&quot;]/div[@class=&quot;relative border rounded-lg p-[16px] lg:w-3/6 w-full border-paletteText-inactive&quot;]/button[@class=&quot;absolute inset-0 w-full h-full bg-transparent&quot;]</value>
      <webElementGuid>7fea77e1-34c4-447f-9094-f69dd38c875e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='product_type']</value>
      <webElementGuid>2fc97ca4-8911-458d-81d0-e9711408f898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>0680d71b-ac07-4379-8550-6f23d23d00bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>55ad5fb7-85a6-4ff8-b83f-e771dc223cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'product_type']</value>
      <webElementGuid>e1d8d7ef-e506-42ff-8e00-c74721a6f217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
