<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rd_jasa</name>
   <tag></tag>
   <elementGuidId>8af83598-9dea-4802-b10a-beb7ed247844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[2]/div[2]/div[2]/div[1]/div/div[$value]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${value}</value>
      <webElementGuid>8c708ca3-48bf-4545-a72f-b48e17405373</webElementGuid>
   </webElementProperties>
</WebElementEntity>
