<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_phonenumber</name>
   <tag></tag>
   <elementGuidId>31ee74c7-1bbb-43e0-bcf2-b2c4717fe7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phonenumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phonenumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d2353fe-1506-4011-86dc-72666e67464d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7545968a-220d-457f-8eb3-c5e015316ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 text-paletteText-primary text-sm w-full focus:outline-none</value>
      <webElementGuid>b7a3888e-1662-4b7d-abd1-92f3e5ec623e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>3560f8c1-00ac-450b-b699-f5cd7516dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>7de55ea6-db4b-4481-a98c-6d9131c3b08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4693ccd-5323-45d4-9fb9-56029383f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123456789</value>
      <webElementGuid>b973b196-65fe-477a-aeef-f7a9c972f594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>fefe3d97-6dd0-4098-9555-923d968c83ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phonenumber&quot;)</value>
      <webElementGuid>ac2e1658-c943-46f8-b23f-49e91110a510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phonenumber']</value>
      <webElementGuid>bb7eced3-0cdd-4006-aafc-6482b30e157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/section/div/div/form/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>b2709973-a104-4fbb-beb5-c187d045661f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>9532fbd7-51b7-48b7-bce6-04cab8bc5147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phonenumber' and @name = 'phonenumber' and @type = 'text' and @placeholder = '8123456789']</value>
      <webElementGuid>164f6441-ddb5-480b-9ba1-6e7eab6cb21e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
