<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_seller_referralcode</name>
   <tag></tag>
   <elementGuidId>b35afb7b-5857-4513-bc65-979eec57fa5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee7bcefc-8ac8-425c-ad72-5bee862c2005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appearance-none border border-paletteText-inactive rounded-lg w-full py-2 px-3 text-grey-darker</value>
      <webElementGuid>9c46897b-e8be-47ef-bd76-16e9e479455f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refCode</value>
      <webElementGuid>3ac67a30-ddd2-442c-a249-2c565d9ec8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refCode</value>
      <webElementGuid>393e2b11-4ce5-42a3-a1a7-403cf29dab53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f16f5e69-94de-44a3-8325-80e9ae759a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode referal</value>
      <webElementGuid>b1277f64-5b60-439d-89b9-54dd53c51700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>`</value>
      <webElementGuid>e69039dc-722a-4be3-b0aa-358f2e505345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refCode&quot;)</value>
      <webElementGuid>3dd6545e-2366-4368-b809-31d8871dd8be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refCode']</value>
      <webElementGuid>067c890e-5830-4608-80a5-b6d16390027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/form/div[4]/input</value>
      <webElementGuid>073a5d51-af24-4948-b795-4e7d6cf3720a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>eda56180-f54c-44cb-9252-feaf26550f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'refCode' and @name = 'refCode' and @type = 'text' and @placeholder = 'Masukkan kode referal']</value>
      <webElementGuid>ac42a983-0dcc-46ef-a757-6a54a5aceaed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
